spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cooperados_db
    username: cooperados_user
    password: cooperados_pass
  
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    validate-on-migrate: true

logging:
  level:
    com.cooperados: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

server:
  port: 8081
