spring:
  application:
    name: cooperados-api
  
  datasource:
    url: jdbc:postgresql://localhost:5432/cooperados_db
    username: cooperados_user
    password: cooperados_pass
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
  
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    validate-on-migrate: true
  
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false

server:
  port: 8080
  servlet:
    context-path: /

# Configurações personalizadas da aplicação
app:
  name: "Cooperados API"
  version: "1.0.0"
  description: "API de Cadastro de Cooperados - Teste Técnico"
  
  database:
    max-pool-size: 20
    min-idle: 5
    connection-timeout: 30000
    idle-timeout: 600000
    max-lifetime: 1800000
  
  security:
    enabled: false
    jwt-secret: "cooperadosSecretKey2024"
    jwt-expiration: 86400000
    allowed-origins: ["*"]

# Configurações de logging
logging:
  level:
    com.cooperados: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Configurações de monitoramento
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

# Configurações de validação
validation:
  cpf:
    enabled: true
  cnpj:
    enabled: true
  telefone:
    enabled: true
  email:
    enabled: true
